import * as apisKeychain from '@/core/apis/keychain';
import * as apisLock from '@/core/apis/lock';
import {
  isAuthenticatedByBiometrics,
  RequestGenericPurpose,
} from '@/core/apis/keychain';
import { getPasswordIsAutoGeneratedSnapshot } from '@/core/serviceApi/preference';
import { toastUnlocking } from '@/utils/toastUnlocking';
import {
  WalletUnlockCancelledError,
  isWalletUnlockCancelled,
} from '@/utils/walletUnlockError';
import { setWalletUnlockRequester } from '@/utils/walletUnlockGuard';

type PendingWalletUnlock = {
  id: number;
  promise: Promise<void>;
  resolve: () => void;
  reject: (error: unknown) => void;
  hideModal?: () => void;
};

type AuthenticationModal2024Module =
  typeof import('@/components/AuthenticationModal/AuthenticationModal2024');

export { WalletUnlockCancelledError, isWalletUnlockCancelled };

let nextUnlockRequestId = 1;
let pendingWalletUnlock: PendingWalletUnlock | null = null;

export async function ensureWalletUnlockedForAction() {
  try {
    await ensureWalletUnlocked();
    return true;
  } catch (error) {
    if (isWalletUnlockCancelled(error)) {
      return false;
    }

    throw error;
  }
}

export function withWalletUnlockForAction<TArgs extends unknown[], TResult>(
  fn: (...args: TArgs) => Promise<TResult>,
  onCancel: (...args: TArgs) => TResult | Promise<TResult>,
) {
  return async (...args: TArgs) => {
    if (!(await ensureWalletUnlockedForAction())) {
      return onCancel(...args);
    }

    return fn(...args);
  };
}

export function cancelPendingWalletUnlock(unlockRequestId?: number) {
  if (!pendingWalletUnlock) {
    return;
  }

  if (
    typeof unlockRequestId === 'number' &&
    pendingWalletUnlock.id !== unlockRequestId
  ) {
    return;
  }

  const { hideModal, reject } = pendingWalletUnlock;
  pendingWalletUnlock = null;
  hideModal?.();
  reject(new WalletUnlockCancelledError());
}

async function canRequestStoredCredentialUnlock() {
  if (getPasswordIsAutoGeneratedSnapshot()) {
    return true;
  }

  if (!isAuthenticatedByBiometrics()) {
    return false;
  }

  const supportedBiometryType = await apisKeychain
    .getSupportedBiometryType()
    .catch(() => null);

  if (supportedBiometryType) {
    return true;
  }

  return false;
}

export async function ensureWalletUnlocked() {
  if (apisLock.isUnlocked()) {
    await apisLock.ensureKeyringRuntimeReady('wallet_unlock_action');
    return;
  }

  if (pendingWalletUnlock) {
    return pendingWalletUnlock.promise.then(() =>
      apisLock.ensureKeyringRuntimeReady('wallet_unlock_action_pending'),
    );
  }

  const unlockRequestId = nextUnlockRequestId++;
  let resolvePending: PendingWalletUnlock['resolve'] = () => {};
  let rejectPending: PendingWalletUnlock['reject'] = () => {};
  const promise = new Promise<void>((resolve, reject) => {
    resolvePending = resolve;
    rejectPending = reject;
  });

  pendingWalletUnlock = {
    id: unlockRequestId,
    promise,
    resolve: resolvePending,
    reject: rejectPending,
  };

  const resolveUnlock = () => {
    if (pendingWalletUnlock?.id !== unlockRequestId) {
      return;
    }

    const { resolve } = pendingWalletUnlock;
    pendingWalletUnlock = null;
    resolve();
  };

  const rejectUnlock = () => {
    if (pendingWalletUnlock?.id !== unlockRequestId) {
      return;
    }

    const { reject } = pendingWalletUnlock;
    pendingWalletUnlock = null;
    reject(new WalletUnlockCancelledError());
  };

  const unlockingToastRef: { hide: (() => void) | null } = {
    hide: null,
  };

  const hideUnlockingToast = () => {
    unlockingToastRef.hide?.();
    unlockingToastRef.hide = null;
  };

  try {
    if (!(await canRequestStoredCredentialUnlock())) {
      throw new Error('Biometrics Disabled');
    }

    await apisKeychain.requestGenericPassword({
      purpose: RequestGenericPurpose.DECRYPT_PWD,
      onPlainPassword: async password => {
        unlockingToastRef.hide = toastUnlocking();

        try {
          await apisLock.verifyPasswordOrUnlock(password);
          resolveUnlock();
        } finally {
          hideUnlockingToast();
        }
      },
    });
  } catch (error) {
    hideUnlockingToast();
    if (__DEV__) {
      console.error(error);
    }

    if (getPasswordIsAutoGeneratedSnapshot()) {
      rejectUnlock();
      return promise.then(() =>
        apisLock.ensureKeyringRuntimeReady('wallet_unlock_action_rejected'),
      );
    }

    const authModalModule =
      require('@/components/AuthenticationModal/AuthenticationModal2024') as AuthenticationModal2024Module;
    const { AuthenticationModal2024 } = authModalModule;
    const { hideModal } = await AuthenticationModal2024.show({
      title: 'Unlock JiuCheng Wallet',
      authType: ['password'],
      onFinished: resolveUnlock,
      onCancel: rejectUnlock,
      onDismiss: rejectUnlock,
      validationHandler(password) {
        return apisLock.verifyPasswordOrUnlock(password);
      },
    });

    if (pendingWalletUnlock?.id === unlockRequestId) {
      pendingWalletUnlock.hideModal = hideModal;
    } else {
      hideModal();
    }
  }

  return promise.then(() =>
    apisLock.ensureKeyringRuntimeReady('wallet_unlock_action_after_request'),
  );
}

setWalletUnlockRequester(ensureWalletUnlocked);
